### ISSUE TITLE
use a production web server

### ISSUE THREAD

**Issue by andrewljohnson** [dkarchmer/aws-eb-docker-django#3]
I was curious if you ever did work to use nginx or apache instead of the django dev server? 

I'd like to deploy an app in exactly this way, but using nginx.

**Comment by dkarchmer** [comment]
See http://stackoverflow.com/questions/29991506/do-i-need-my-own-server-if-i-move-my-elastic-beanstalk-app-to-use-docker (both answers). I don't feel I really know the answer.

In fact, I personally stayed away from using docker for the front-end. I only use it for my worker tier. For the front-end server, I felt the Elastic Beanstalk Python environment is safer. See https://github.com/dkarchmer/django-aws-template for what I really use in production. I do use docker for development and specially testing, but deploy to the regular python environment

But if I was to use Docker for the front end, I would recommend using the newer multi-containter version, and have the NGINX running on one container, and Django on the other.

**Comment by andrewljohnson** [comment]
Thanks, I appreciate your comments.
